/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fees_management_system;

import java.awt.Color;

/**
 *
 * @author vaish
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_addFess = new javax.swing.JPanel();
        lbl_Addfees = new javax.swing.JLabel();
        panel_ViewRecord = new javax.swing.JPanel();
        lbl_ViewRe = new javax.swing.JLabel();
        panel_ViewReport = new javax.swing.JPanel();
        lbl_ViewReport = new javax.swing.JLabel();
        panel_viewC = new javax.swing.JPanel();
        lblViewc = new javax.swing.JLabel();
        panle_SRecord = new javax.swing.JPanel();
        lbl_Srecord = new javax.swing.JLabel();
        panel_EditC = new javax.swing.JPanel();
        lbl_EditC = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 212, 208));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_addFess.setBackground(new java.awt.Color(30, 81, 81));
        panel_addFess.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        panel_addFess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_addFessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_addFessMouseExited(evt);
            }
        });
        panel_addFess.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Addfees.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lbl_Addfees.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Addfees.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaish\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\Fees_Management_Images\\plus.png")); // NOI18N
        lbl_Addfees.setText(" Add Fees");
        lbl_Addfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AddfeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_AddfeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_AddfeesMouseExited(evt);
            }
        });
        panel_addFess.add(lbl_Addfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 160));

        jPanel1.add(panel_addFess, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 320, 170));

        panel_ViewRecord.setBackground(new java.awt.Color(30, 81, 81));
        panel_ViewRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        panel_ViewRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ViewRe.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lbl_ViewRe.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ViewRe.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaish\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\Fees_Management_Images\\view all record.png")); // NOI18N
        lbl_ViewRe.setText("  View Record");
        lbl_ViewRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ViewReMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ViewReMouseExited(evt);
            }
        });
        panel_ViewRecord.add(lbl_ViewRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 160));

        jPanel1.add(panel_ViewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 70, 330, 170));

        panel_ViewReport.setBackground(new java.awt.Color(30, 81, 81));
        panel_ViewReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        panel_ViewReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_ViewReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_ViewReportMouseExited(evt);
            }
        });
        panel_ViewReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ViewReport.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lbl_ViewReport.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ViewReport.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaish\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\Fees_Management_Images\\view report.png")); // NOI18N
        lbl_ViewReport.setText("  View Report");
        panel_ViewReport.add(lbl_ViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 160));

        jPanel1.add(panel_ViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 390, 320, 170));

        panel_viewC.setBackground(new java.awt.Color(30, 81, 81));
        panel_viewC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        panel_viewC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_viewCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_viewCMouseExited(evt);
            }
        });
        panel_viewC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewc.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblViewc.setForeground(new java.awt.Color(255, 255, 255));
        lblViewc.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaish\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\Fees_Management_Images\\text-book-opened-from-top-view.png")); // NOI18N
        lblViewc.setText("  View Course");
        panel_viewC.add(lblViewc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 310, 160));

        jPanel1.add(panel_viewC, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 330, 170));

        panle_SRecord.setBackground(new java.awt.Color(30, 81, 81));
        panle_SRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        panle_SRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Srecord.setBackground(new java.awt.Color(30, 81, 81));
        lbl_Srecord.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lbl_Srecord.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Srecord.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaish\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\Fees_Management_Images\\search-document.png")); // NOI18N
        lbl_Srecord.setText("Search Record");
        lbl_Srecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_SrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_SrecordMouseExited(evt);
            }
        });
        panle_SRecord.add(lbl_Srecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 160));

        jPanel1.add(panle_SRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 330, 170));

        panel_EditC.setBackground(new java.awt.Color(30, 81, 81));
        panel_EditC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        panel_EditC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_EditCMouseExited(evt);
            }
        });
        panel_EditC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_EditC.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lbl_EditC.setForeground(new java.awt.Color(255, 255, 255));
        lbl_EditC.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaish\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\Fees_Management_Images\\edit.png")); // NOI18N
        lbl_EditC.setText("    Edit Course");
        lbl_EditC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_EditCMouseEntered(evt);
            }
        });
        panel_EditC.add(lbl_EditC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 310, 140));

        jPanel1.add(panel_EditC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 320, 170));

        jPanel9.setBackground(new java.awt.Color(30, 81, 81));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 180, 90));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaish\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\Fees_Management_Images\\about.png")); // NOI18N
        jLabel7.setText("  About");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 90));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 700, 180, 90));

        jPanel11.setBackground(new java.awt.Color(30, 81, 81));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 180, 90));

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(0, 102, 102));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 180, 90));

        jPanel15.setBackground(new java.awt.Color(0, 102, 102));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(0, 102, 102));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 180, 90));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 180, 90));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 180, 90));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\vaish\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\Fees_Management_Images\\logout.png")); // NOI18N
        jLabel8.setText("    Logout");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 180, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1930, 800));

        jPanel2.setBackground(new java.awt.Color(30, 81, 81));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Department of Technical Education, Skill Development and Employment");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 810, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bhopal,462033 Madhya Pradesh, INDIA");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 370, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rajiv Gandhi Proudyogiki Vishwavidyalaya");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 560, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_AddfeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AddfeesMouseEntered
     
        Color clr=new Color(176,212,208);
        panel_addFess.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_AddfeesMouseEntered

    private void lbl_AddfeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AddfeesMouseExited

        Color clr=new Color(30,81,81);
        panel_addFess.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_AddfeesMouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        


// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void lbl_SrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SrecordMouseEntered

       Color clr=new Color(176,212,208);
        panle_SRecord.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_SrecordMouseEntered

    private void lbl_SrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SrecordMouseExited

        Color clr=new Color(30,81,81);
        panle_SRecord.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_SrecordMouseExited

    private void lbl_ViewReMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ViewReMouseEntered

Color clr=new Color(176,212,208);
        panel_ViewRecord.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ViewReMouseEntered

    private void lbl_ViewReMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ViewReMouseExited

Color clr=new Color(30,81,81);
        panel_ViewRecord.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ViewReMouseExited

    private void lbl_EditCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_EditCMouseEntered

Color clr=new Color(176,212,208);
        panel_EditC.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_EditCMouseEntered

    private void panel_EditCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_EditCMouseExited

Color clr=new Color(30,81,81);
        panel_EditC.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_EditCMouseExited

    private void panel_viewCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_viewCMouseEntered
   Color clr=new Color(176,212,208);
        panel_viewC.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_viewCMouseEntered

    private void panel_viewCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_viewCMouseExited
Color clr=new Color(30,81,81);
        panel_viewC.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_viewCMouseExited

    private void panel_ViewReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ViewReportMouseEntered
Color clr=new Color(176,212,208);
        panel_ViewReport.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_panel_ViewReportMouseEntered

    private void panel_ViewReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ViewReportMouseExited

        Color clr=new Color(30,81,81);
        panel_ViewReport.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_panel_ViewReportMouseExited

    private void lbl_AddfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AddfeesMouseClicked

        Add_fee Addf=new Add_fee();
        Addf.setVisible(true);
        this.dispose();

        
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_AddfeesMouseClicked

    private void panel_addFessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_addFessMouseEntered

Color clr=new Color(176,212,208);
        panel_addFess.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_panel_addFessMouseEntered

    private void panel_addFessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_addFessMouseExited

        Color clr=new Color(30,81,81);
        panel_addFess.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_panel_addFessMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblViewc;
    private javax.swing.JLabel lbl_Addfees;
    private javax.swing.JLabel lbl_EditC;
    private javax.swing.JLabel lbl_Srecord;
    private javax.swing.JLabel lbl_ViewRe;
    private javax.swing.JLabel lbl_ViewReport;
    private javax.swing.JPanel panel_EditC;
    private javax.swing.JPanel panel_ViewRecord;
    private javax.swing.JPanel panel_ViewReport;
    private javax.swing.JPanel panel_addFess;
    private javax.swing.JPanel panel_viewC;
    private javax.swing.JPanel panle_SRecord;
    // End of variables declaration//GEN-END:variables
}
